# Generated by Django 2.1.2 on 2018-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_remove_mypurchases_notes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypurchases',
            name='random',
            field=models.CharField(default='Random', max_length=52),
        ),
    ]
