# Generated by Django 2.1.2 on 2018-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0003_mypurchases_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypurchases',
            name='notes_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
