# Generated by Django 2.1.2 on 2018-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0004_mypurchases_notes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypurchases',
            name='notes_id',
            field=models.IntegerField(default=0),
        ),
    ]
