# Generated by Django 2.1.2 on 2018-11-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0005_auto_20181110_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypurchases',
            name='notes_id',
            field=models.IntegerField(),
        ),
    ]
