# Generated by Django 2.1.2 on 2018-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0006_auto_20181110_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypurchases',
            name='random',
        ),
        migrations.AlterField(
            model_name='mypurchases',
            name='notes_id',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
