# Generated by Django 2.1.2 on 2018-11-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Notes', unique=True),
        ),
    ]
