# Generated by Django 2.1.2 on 2018-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zip', models.CharField(max_length=60)),
                ('states', models.CharField(max_length=60)),
                ('nameOnCard', models.CharField(max_length=60)),
                ('creditCardNum', models.CharField(max_length=60)),
                ('expmonth', models.CharField(max_length=60)),
                ('cvv', models.CharField(max_length=60)),
                ('expYear', models.CharField(max_length=60)),
            ],
        ),
    ]
