# Generated by Django 2.1.2 on 2018-10-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=60, unique=True)),
                ('cat_slug', models.SlugField(max_length=80, unique=True)),
                ('cat_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('cat_name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_user', models.CharField(max_length=60, unique=True)),
                ('buyer_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('buyer_commentary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=60, unique=True)),
                ('note_slug', models.SlugField(max_length=80, unique=True)),
                ('note_summary', models.TextField(blank=True)),
                ('note_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note_snippet', models.ImageField(blank=True, upload_to='Notes')),
                ('note_image1', models.ImageField(blank=True, upload_to='Notes')),
                ('note_image2', models.ImageField(blank=True, upload_to='Notes')),
                ('note_image3', models.ImageField(blank=True, upload_to='Notes')),
                ('note_date_created', models.DateTimeField(auto_now_add=True)),
                ('note_updated', models.DateTimeField(auto_now=True)),
                ('note_times_purchased', models.IntegerField(default=0)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note_uploader_user', models.CharField(max_length=60, unique=True)),
                ('note_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Category')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ('note_name',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='seller_note_being_reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Notes'),
        ),
    ]
