# Generated by Django 2.1.2 on 2018-10-20 16:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('market', '0003_auto_20181020_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
    ]
