# Generated by Django 2.1.2 on 2018-10-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20181020_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_uploader_user',
            field=models.CharField(max_length=60),
        ),
    ]
