# Generated by Django 2.1.2 on 2018-11-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20181022_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_created',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('note_name',), 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note_category',
            new_name='category',
        ),
    ]
