# Generated by Django 2.1.2 on 2018-11-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20181102_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note_slug',
            new_name='slug',
        ),
    ]
