# Generated by Django 2.1.2 on 2018-11-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_comment_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='buyer_user',
            field=models.CharField(max_length=60),
        ),
    ]
