# Generated by Django 2.1.2 on 2018-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20181109_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='buyer_rating',
            field=models.IntegerField(default=-1),
        ),
    ]
