# Generated by Django 2.1.2 on 2018-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20181110_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='blank_stars',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='notes',
            name='full_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notes',
            name='partial_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='buyer_rating',
            field=models.IntegerField(default=0),
        ),
    ]
