# Generated by Django 2.1.2 on 2018-11-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20181122_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='blank_stars',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='full_star',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='partial_star',
        ),
    ]
